# Generated by Django 5.0.4 on 2024-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('imgUrl1', models.URLField()),
                ('imgUrl2', models.URLField()),
                ('trackUrl', models.URLField()),
                ('previewUrl', models.URLField()),
            ],
        ),
    ]
